version: '3'

services:

  visualizer:
    image: jahrik/arm-visualizer:aarch64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    # - 8081:8080
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.network=traefik
        - traefik.http.routers.visualizer.tls=true
        - traefik.http.routers.visualizer.service=visualizer
        - traefik.http.routers.visualizer.rule=Host(`visualizer.homelab.business`)
        - traefik.http.routers.visualizer.middlewares=visualizer-auth
        - traefik.http.routers.visualizer.entrypoints=web,websecure
        - traefik.http.services.visualizer.loadbalancer.server.port=8080
        - traefik.http.middlewares.visualizer-auth.basicauth.usersfile=/etc/traefik/.htpasswd

      placement:
        constraints:
          - node.labels.arch == aarch64

networks:
  traefik:
    driver: overlay
    external: true
